#!/bin/sh

# Convenience script for running SWIG before it is installed.
# Intended for ad-hoc usage and not by the test-suite or examples.

builddir=`dirname "$0"`
SWIG_LIB='/home/peter/projects/swig4/swig-4.0.1/Lib'
export SWIG_LIB
exec "$builddir/swig" "$@"
